### ISSUE TITLE
Generating development JavaScript bundle failed

### ISSUE THREAD

**Issue by NguyenDa18** [jamrants/donations#39]
JS bundle failing to build and getting build errors on running `gatsby develop` after installing NPM packages. I believe it is because I am missing the config for environment variables process.env.AIRTABLE_KEY and process.env.BASE_ID. Is there publicly shareable configuration we can use to connect to your Airtable data?

```
There was an error in your GraphQL query:

Cannot query field "allAirtable" on type "Query".

If you don't expect "allAirtable" to exist on the type "Query" it is most likely a typo.
However, if you expect "allAirtable" to exist there are a couple of solutions to common problems:
```

```
There was an error in your GraphQL query:

Cannot query field "allAirtableCountryIncomes" on type "Query".

If you don't expect "allAirtableCountryIncomes" to exist on the type "Query" it is most likely a typo.
However, if you expect "allAirtableCountryIncomes" to exist there are a couple of solutions to common problems:
```

**Comment by davidli3100** [comment]
Hi Danh,

I if you head over to https://airtable.com/shrb6pZwkGX6rLIQa - all of our raw data is here.
The airtable key we're using is actually for my entire airtable account so I wouldn't be able to share that publicly. 

You could however copy the data into your own airtable and use a key from there.

**Comment by jhthenerd** [comment]
I've gone ahead and added some more info about this in #40, as well as enabling copying the base via the link above within the sharing settings.
