### ISSUE TITLE
FSA and ZIP Links are Broken

### ISSUE THREAD

**Issue by err53** [jamrants/donations#51]
**Describe the bug**
The FSA and ZIP links do not lead to a valid location

**To Reproduce**

1. Go to https://donations.exposed/about/
2. Click on the `FSA` or `ZIP codes` link

**Expected behavior**
An Airtable Base appears

**Comment by RetroCraft** [comment]
I (shortsightedly) deleted the Airtables after pushing the raw data through Git LFS to [jamrants/donations-api](https://github.com/jamrants/donations-api).

They've been restored.
